import type { Invitation, InvitationData } from "@/lib/types/invitation";

export const DEMO_INVITATION_ID = "demo-invitation";
export const DEMO_SLUG = "demo";
export const DEMO_STORAGE_KEY = "demo_invitation_data";
export const DEMO_DATA_VERSION = "6";

export const demoInvitationData: InvitationData = {
  "date": "2027-01-13",
  "time": "4:00 PM",
  "andText": "&",
  "herName": "Isabella",
  "hisName": "Alexander",
  "bodyFont": "Inter",
  "heroIcon": "initial",
  "nameType": "couple",
  "sections": {
    "map": true,
    "rsvp": true,
    "footer": true,
    "gallery": true,
    "timeline": true,
    "countdown": true,
    "dresscode": true,
    "entourage": true,
    "giftguide": true,
    "eventdetails": true,
    "weddingdirectory": true
  },
  "subtitle": "Together with their families",
  "timezone": "PST",
  "entourage": {
    "couple": {
      "title": "Couple",
      "brideName": "Isabella Marie Johnson",
      "groomName": "Alexander James Smith",
      "brideTitle": "Bride",
      "groomTitle": "Groom"
    },
    "header": "The Wedding Party",
    "topText": "Together with their families",
    "bottomText": "We thank you for being part of our special day",
    "namesColor": "#8a6252",
    "paperColor": "#f5e3db",
    "titlesColor": "#5c4a3a",
    "brideParents": {
      "title": "Parents of the Bride",
      "fatherName": "Michael Johnson",
      "motherName": "Sarah Johnson",
      "fatherTitle": "Mr.",
      "motherTitle": "Mrs."
    },
    "groomParents": {
      "title": "Parents of the Groom",
      "fatherName": "Robert Smith",
      "motherName": "Elizabeth Smith",
      "fatherTitle": "Mr.",
      "motherTitle": "Mrs."
    },
    "namesFontSize": 125,
    "titlesFontSize": 106,
    "namesTypography": "Inter",
    "paperBackground": "texture5",
    "visibleSections": {
      "couple": true,
      "ushers": false,
      "bestMan": false,
      "chairman": false,
      "groomsmen": false,
      "witnesses": false,
      "ringBearer": false,
      "usherettes": false,
      "bibleBearer": false,
      "bridesmaids": false,
      "flowerGirls": false,
      "jrGroomsmen": false,
      "maidOfHonor": false,
      "brideParents": true,
      "groomParents": true,
      "jrBridesmaid": false,
      "directorOfFeast": false,
      "directorOfCeremony": false,
      "marriageTalkSpeaker": false,
      "officiatingMinister": false
    },
    "titlesTypography": "Playfair Display"
  },
  "venueName": "The Grand Ballroom",
  "coupleName": "Alexander & Isabella",
  "mainColor1": "#fff8f3",
  "mainColor2": "#b88a78",
  "mapHeading": "Location",
  "mapMessage": "Join us at this beautiful venue",
  "musicTrack": "",
  "giftMessage": "Your presence is our greatest gift",
  "headingFont": "Playfair Display",
  "heroMessage": "We invite you to celebrate with us",
  "musicVolume": 50,
  "rsvpHeading": "RSVP",
  "venueImages": [],
  "venueLayout": {
    "doors": [],
    "tables": [],
    "cutouts": [],
    "baseShape": "rectangle",
    "gridColor": "#e5e7eb",
    "chairColor": "#9ca3af",
    "dimensions": {
      "width": 800,
      "height": 600
    },
    "floorColor": "#f3f4f6",
    "tableColor": "#ffffff",
    "tableScale": 1,
    "gridDensity": 20,
    "outlineColor": "#6b7280",
    "doorColorMode": 0,
    "tableTextColor": "#374151"
  },
  "baseFontSize": 16,
  "heroIconSize": 100,
  "heroIconType": "initial",
  "heroNameSize": 62.5,
  "musicEnabled": false,
  "rsvpDeadline": "2026-12-14",
  "rsvpInvitees": [],
  "sectionOrder": [
    "hero",
    "wedding-directory",
    "countdown",
    "event-details",
    "entourage",
    "dresscode",
    "gallery",
    "map",
    "timeline",
    "rsvp",
    "giftguide",
    "footer"
  ],
  "venueAddress": "123 Wedding Lane, Romance City",
  "dresscodeBody": "Formal attire requested",
  "footerDivider": "none",
  "galleryImages": [
    ""
  ],
  "neutralColor1": "#5c4a3a",
  "neutralColor2": "#8a6252",
  "galleryHeading": "Gallery",
  "galleryMessage": "A glimpse of our journey",
  "rsvpGuestField": true,
  "rsvpPaperColor": "#ffffff",
  "timelineEvents": [],
  "backgroundImage": "",
  "backgroundMusic": [],
  "heroOthersColor": "#ffffff",
  "imageTransforms": {},
  "mapHeadingColor": "#5c4a3a",
  "mapMessageColor": "#8a6252",
  "mapUseMainColor": true,
  "welcomeElements": {},
  "welcomeEnvelope": "classic-envelope",
  "countdownHeading": "Countdown",
  "countdownMessage": "Until we say I do",
  "dresscodeHeading": "Dress Code",
  "entourageHeading": "Entourage",
  "flowerDecoration": "none",
  "giftguideHeading": "Gifts",
  "rsvpCrystalColor": "#b88a78",
  "rsvpDeadlineText": "Please respond by",
  "rsvpGuestDetails": {},
  "rsvpMessageField": true,
  "rsvpReservedText": "Reserved",
  "rsvpUseMainColor": true,
  "universalDivider": "none",
  "countdownShowDate": true,
  "galleryGridLayout": "grid-2",
  "heroAmpersandSize": 100,
  "heroDateStructure": "default",
  "heroHostLineImage": "hostline-01",
  "heroIconColorTint": "#b88a78",
  "heroIconTextColor": "#ffffff",
  "heroOverlayColor1": "#b88a78",
  "heroOverlayColor2": "#8a6252",
  "mapBackgroundType": "color",
  "welcomeScreenType": "classic-envelope",
  "dresscodeBodyColor": "#8a6252",
  "heroIconName2First": false,
  "heroIconTypography": "Playfair Display",
  "heroOthersTextSize": 1,
  "heroVenueStructure": "default",
  "mapBackgroundColor": "#fff8f3",
  "mapHeadingFontSize": 100,
  "mapMessageFontSize": 100,
  "rsvpAttendanceText": "Number of guests",
  "rsvpBackgroundType": "color",
  "rsvpGuestNameStyle": 0,
  "rsvpHeaderFontSize": 100,
  "dressCodeCategories": [],
  "eventDetailsDivider": "none",
  "eventDetailsHeading": "Event Details",
  "eventDetailsMessage": "We would be delighted to have you join us",
  "galleryHeadingColor": "#5c4a3a",
  "galleryMessageColor": "#8a6252",
  "galleryUseMainColor": true,
  "giftThankYouMessage": "Thank you for your generosity",
  "heroOverlayOpacity1": 0.5,
  "heroOverlayOpacity2": 0.5,
  "rsvpBackgroundColor": "#fff8f3",
  "rsvpCardHeadingText": "Will you be attending?",
  "rsvpPaperBackground": "texture1",
  "rsvpTopTextFontSize": 100,
  "heroAmpersandOpacity": 100,
  "heroBackgroundImages": [],
  "heroClosingSentiment": "With love",
  "heroIconAddAmpersand": true,
  "heroOthersTypography": "Inter",
  "mapHeadingTypography": "Playfair Display",
  "mapMessageTypography": "Inter",
  "countdownCrystalColor": "#b88a78",
  "countdownHeadingColor": "#5c4a3a",
  "countdownMessageColor": "#8a6252",
  "countdownUseMainColor": true,
  "dresscodeBodyFontSize": 100,
  "dresscodeHeadingColor": "#5c4a3a",
  "dresscodeUseMainColor": true,
  "entourageHeadingColor": "#5c4a3a",
  "entourageTopTextColor": "#8a6252",
  "entourageUseMainColor": true,
  "galleryBackgroundType": "color",
  "heroAmpersandPosition": "default",
  "heroBackgroundOverlay": "solid",
  "heroDateStructureSize": 100,
  "heroTextShadowOpacity": 0.1,
  "weddingDirectoryItems": [
    {
      "id": "weddir-item-1784292053496",
      "layers": [
        {
          "id": "body-1",
          "tint": "#ffd2b3",
          "zIndex": 1,
          "designId": "default"
        },
        {
          "id": "body-2",
          "tint": "#fff8f3",
          "zIndex": 2,
          "designId": "default"
        },
        {
          "id": "outline",
          "tint": "#fff8f3",
          "zIndex": 3,
          "designId": "default"
        }
      ],
      "rotate": 0,
      "shadow": {
        "blur": 10,
        "color": "#000000",
        "enabled": false,
        "offsetX": 0,
        "offsetY": 4
      },
      "zIndex": 1,
      "pattern": "1",
      "imageUrl": "",
      "animation": {
        "type": "none",
        "scrollTrigger": 50
      },
      "positionX": 0,
      "positionY": 0,
      "stampTint": "#ffd2b3",
      "cardVariant": 0,
      "scaleMobile": 2,
      "excludeTexts": false,
      "hostLineText": "Please join us as we celebrate our love and commitment",
      "nameTextSize": 1,
      "scaleDesktop": 1,
      "flowerVariant": 0,
      "targetSection": "event-details",
      "textAnimation": "blur-glow",
      "stampTextColor": "#ffd2b3",
      "draftDesignType": "envelope",
      "positionXMobile": 0,
      "positionYMobile": 0,
      "photoPapersText1": "",
      "photoPapersText2": "",
      "positionXDesktop": 0,
      "positionYDesktop": 0,
      "photoPapersImage1": "",
      "photoPapersImage2": "",
      "finalSentimentText": "With all our love, we look forward to celebrating with you.",
      "stampTextBlendMode": "screen",
      "photoPapersFontType": "Playfair Display",
      "swapPhotoAndFlowers": false,
      "photoPapersTextColor": "#333333"
    }
  ],
  "countdownDateStructure": "default",
  "galleryBackgroundColor": "#fff8f3",
  "galleryHeadingFontSize": 100,
  "galleryMessageFontSize": 100,
  "rsvpBottomTextFontSize": 100,
  "countdownBackgroundType": "color",
  "dresscodeBackgroundType": "color",
  "dresscodeTitlesFontSize": 100,
  "entourageBackgroundType": "color",
  "heroAmpersandTypography": "Playfair Display",
  "rsvpEntourageHonorifics": {},
  "weddingDirectoryHeading": "Wedding Directory",
  "weddingDirectoryMessage": "Our wonderful team",
  "backgroundMusicFileNames": [],
  "countdownBackgroundColor": "#fff8f3",
  "countdownHeadingFontSize": 100,
  "countdownMessageFontSize": 100,
  "dresscodeBackgroundColor": "#fff8f3",
  "entourageBackgroundColor": "#fff8f3",
  "entourageBottomTextColor": "#8a6252",
  "entourageHeadingFontSize": 100,
  "entourageTopTextFontSize": 100,
  "eventDetailsHeadingColor": "#5c4a3a",
  "eventDetailsMessageColor": "#b88a78",
  "eventDetailsUseMainColor": false,
  "galleryHeadingTypography": "Playfair Display",
  "galleryMessageTypography": "Inter",
  "heroBackgroundImagesCrop": [],
  "heroDateStructureSpacing": 100,
  "heroHostLineImageOpacity": 1,
  "heroIconColorTintOpacity": 0.3,
  "heroIconMarginAdjustment": 0,
  "heroClosingSentimentImage": "fsentiment-01",
  "heroDisplayNameTypography": "Playfair Display",
  "rsvpAttendingThankYouText": "Thank you for celebrating with us!",
  "rsvpEntourageGuestDetails": {},
  "countdownHeadingTypography": "Playfair Display",
  "countdownMessageTypography": "Inter",
  "entourageHeadingTypography": "Playfair Display",
  "entourageTopTextTypography": "Inter",
  "eventDetailsBackgroundType": "color",
  "heroBackgroundImagesMobile": [],
  "entourageBottomTextFontSize": 100,
  "eventDetailsBackgroundColor": "#fff8f3",
  "eventDetailsHeadingFontSize": 100,
  "eventDetailsMessageFontSize": 100,
  "rsvpNotAttendingThankYouText": "Thank you for letting us know.",
  "weddingDirectoryHeadingColor": "#5c4a3a",
  "weddingDirectoryMessageColor": "#8a6252",
  "weddingDirectoryUseMainColor": true,
  "entourageBottomTextTypography": "Inter",
  "eventDetailsHeadingTypography": "Playfair Display",
  "eventDetailsMessageTypography": "Inter",
  "heroIconAmpersandOnSecondLine": false,
  "eventDetailsTimelineAccentMode": 0,
  "heroBackgroundImagesMobileCrop": [],
  "weddingDirectoryBackgroundType": "color",
  "weddingDirectoryBackgroundColor": "#fff8f3",
  "weddingDirectoryHeadingFontSize": 100,
  "weddingDirectoryMessageFontSize": 100,
  "heroClosingSentimentImageOpacity": 1,
  "weddingDirectoryHeadingTypography": "Playfair Display",
  "weddingDirectoryMessageTypography": "Inter",
  "rsvpNotAttendingWithMessageThankYouText": "Thank you for your kind words.",
  "accentColor": "#b88a78"
};;;

export const createDemoInvitation = (): Invitation => ({
  id: DEMO_INVITATION_ID,
  slug: DEMO_SLUG,
  accessCode: "DEMO",
  templateId: "demo",
  eventType: "wedding",
  clientName: "Demo Couple",
  data: demoInvitationData,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
});

export const loadDemoInvitation = (): Invitation => {
  if (typeof window === "undefined") return createDemoInvitation();
  const stored = localStorage.getItem(DEMO_STORAGE_KEY);
  const storedVersion = localStorage.getItem(`${DEMO_STORAGE_KEY}_version`);

  // Reset stored demo data if version mismatch (demo data structure changed)
  if (!storedVersion || storedVersion !== DEMO_DATA_VERSION) {
    localStorage.setItem(`${DEMO_STORAGE_KEY}_version`, DEMO_DATA_VERSION);
    return createDemoInvitation();
  }

  if (stored) {
    try {
      const parsed = JSON.parse(stored);
      return { ...createDemoInvitation(), data: { ...demoInvitationData, ...parsed.data } };
    } catch {
      return createDemoInvitation();
    }
  }
  return createDemoInvitation();
};

export const saveDemoInvitation = (data: InvitationData): void => {
  if (typeof window === "undefined") return;
  localStorage.setItem(DEMO_STORAGE_KEY, JSON.stringify({ data }));
};

export const clearDemoInvitation = (): void => {
  if (typeof window === "undefined") return;
  localStorage.removeItem(DEMO_STORAGE_KEY);
};
