import type { Invitation, InvitationData } from "@/lib/types/invitation";

export const DEMO_INVITATION_ID = "demo-invitation";
export const DEMO_SLUG = "demo";
export const DEMO_STORAGE_KEY = "demo_invitation_data";

export const demoInvitationData: InvitationData = {
  nameType: "couple",
  coupleName: "Alexander & Isabella",
  hisName: "Alexander",
  andText: "&",
  herName: "Isabella",
  subtitle: "Together with their families",
  date: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
  time: "4:00 PM",
  timezone: "PST",
  venueName: "The Grand Ballroom",
  venueAddress: "123 Wedding Lane, Romance City",
  headingFont: "Playfair Display",
  bodyFont: "Inter",
  mainColor1: "#fff8f3",
  mainColor2: "#b88a78",
  neutralColor1: "#5c4a3a",
  neutralColor2: "#8a6252",
  accentColor: "#2563EB",
  baseFontSize: 16,
  welcomeEnvelope: "classic-envelope",
  flowerDecoration: "none",
  backgroundImage: "",
  galleryImages: [],
  musicEnabled: false,
  musicTrack: "",
  musicVolume: 50,
  sections: {
    eventdetails: true,
    gallery: true,
    map: true,
    rsvp: true,
    timeline: true,
    countdown: true,
    dresscode: true,
    giftguide: true,
    footer: true,
    entourage: true,
    weddingdirectory: true,
  },
  sectionOrder: ["hero", "eventdetails", "countdown", "entourage", "gallery", "map", "rsvp", "dresscode", "giftguide", "timeline", "footer"],
  heroMessage: "We invite you to celebrate with us",
  heroClosingSentiment: "fsentiment-01",
  heroIcon: "ring",
  heroIconType: "image",
  heroIconColorTint: "#b88a78",
  heroIconColorTintOpacity: 0.3,
  heroIconMarginAdjustment: 0,
  heroIconSize: 100,
  heroIconTypography: "Playfair Display",
  heroIconTextColor: "#ffffff",
  heroIconName2First: false,
  heroIconAddAmpersand: true,
  heroIconAmpersandOnSecondLine: false,
  heroAmpersandPosition: "default",
  heroDisplayNameTypography: "Playfair Display",
  heroAmpersandTypography: "Playfair Display",
  heroDateStructure: "default",
  heroDateStructureSize: 100,
  heroDateStructureSpacing: 0,
  heroVenueStructure: "default",
  heroHostLineImage: "hostline-00",
  heroHostLineImageOpacity: 1,
  heroClosingSentimentImage: "fsentiment-01",
  heroClosingSentimentImageOpacity: 1,
  heroOthersTextSize: 14,
  heroTextShadowOpacity: 0.1,
  heroNameSize: 100,
  heroAmpersandSize: 100,
  heroAmpersandOpacity: 1,
  heroOthersColor: "#ffffff",
  heroOthersTypography: "Inter",
  heroBackgroundOverlay: "solid",
  heroOverlayColor1: "#b88a78",
  heroOverlayColor2: "#8a6252",
  heroOverlayOpacity1: 0.5,
  heroOverlayOpacity2: 0.5,
  eventDetailsHeading: "Event Details",
  eventDetailsMessage: "We would be delighted to have you join us",
  eventDetailsHeadingTypography: "Playfair Display",
  eventDetailsHeadingFontSize: 24,
  eventDetailsMessageTypography: "Inter",
  eventDetailsMessageFontSize: 14,
  eventDetailsHeadingColor: "#5c4a3a",
  eventDetailsMessageColor: "#8a6252",
  eventDetailsUseMainColor: true,
  eventDetailsBackgroundColor: "#fff8f3",
  eventDetailsBackgroundType: "color",
  eventDetailsDivider: "none",
  galleryHeading: "Gallery",
  galleryMessage: "A glimpse of our journey",
  galleryHeadingTypography: "Playfair Display",
  galleryHeadingFontSize: 24,
  galleryMessageTypography: "Inter",
  galleryMessageFontSize: 14,
  galleryHeadingColor: "#5c4a3a",
  galleryMessageColor: "#8a6252",
  galleryUseMainColor: true,
  galleryBackgroundColor: "#fff8f3",
  galleryBackgroundType: "color",
  galleryGridLayout: "grid-2",
  mapHeading: "Location",
  mapMessage: "Join us at this beautiful venue",
  mapHeadingTypography: "Playfair Display",
  mapHeadingFontSize: 24,
  mapMessageTypography: "Inter",
  mapMessageFontSize: 14,
  mapHeadingColor: "#5c4a3a",
  mapMessageColor: "#8a6252",
  mapUseMainColor: true,
  mapBackgroundColor: "#fff8f3",
  mapBackgroundType: "color",
  rsvpHeading: "RSVP",
  rsvpDeadline: new Date(Date.now() + 150 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
  rsvpGuestField: true,
  rsvpMessageField: true,
  rsvpUseMainColor: true,
  rsvpCrystalColor: "#b88a78",
  rsvpBackgroundColor: "#fff8f3",
  rsvpBackgroundType: "color",
  rsvpPaperColor: "#ffffff",
  rsvpPaperBackground: "texture1",
  rsvpCardHeadingText: "Will you be attending?",
  rsvpDeadlineText: "Please respond by",
  rsvpAttendanceText: "Number of guests",
  rsvpGuestNameStyle: 0,
  rsvpReservedText: "Reserved",
  rsvpAttendingThankYouText: "Thank you for celebrating with us!",
  rsvpNotAttendingThankYouText: "Thank you for letting us know.",
  rsvpNotAttendingWithMessageThankYouText: "Thank you for your kind words.",
  countdownHeading: "Countdown",
  countdownMessage: "Until we say I do",
  countdownHeadingTypography: "Playfair Display",
  countdownHeadingFontSize: 24,
  countdownMessageTypography: "Inter",
  countdownMessageFontSize: 14,
  countdownHeadingColor: "#5c4a3a",
  countdownMessageColor: "#8a6252",
  countdownUseMainColor: true,
  countdownBackgroundColor: "#fff8f3",
  countdownBackgroundType: "color",
  countdownShowDate: true,
  countdownCrystalColor: "#b88a78",
  countdownDateStructure: "default",
  dresscodeHeading: "Dress Code",
  dresscodeBody: "Formal attire requested",
  dresscodeHeadingColor: "#5c4a3a",
  dresscodeBodyColor: "#8a6252",
  dresscodeUseMainColor: true,
  dresscodeBackgroundColor: "#fff8f3",
  dresscodeBackgroundType: "color",
  giftguideHeading: "Gifts",
  giftMessage: "Your presence is our greatest gift",
  giftThankYouMessage: "Thank you for your generosity",
  weddingDirectoryHeading: "Wedding Directory",
  weddingDirectoryMessage: "Our wonderful team",
  weddingDirectoryHeadingTypography: "Playfair Display",
  weddingDirectoryHeadingFontSize: 24,
  weddingDirectoryMessageTypography: "Inter",
  weddingDirectoryMessageFontSize: 14,
  weddingDirectoryHeadingColor: "#5c4a3a",
  weddingDirectoryMessageColor: "#8a6252",
  weddingDirectoryUseMainColor: true,
  weddingDirectoryBackgroundColor: "#fff8f3",
  weddingDirectoryBackgroundType: "color",
  entourageHeading: "Entourage",
  entourageHeadingTypography: "Playfair Display",
  entourageHeadingFontSize: 24,
  entourageHeadingColor: "#5c4a3a",
  entourageTopTextTypography: "Inter",
  entourageTopTextFontSize: 12,
  entourageTopTextColor: "#8a6252",
  entourageBottomTextTypography: "Inter",
  entourageBottomTextFontSize: 12,
  entourageBottomTextColor: "#8a6252",
  entourageUseMainColor: true,
  entourageBackgroundColor: "#fff8f3",
  entourageBackgroundType: "color",
  entourage: {
    topText: "Together with their families",
    header: "The Wedding Party",
    bottomText: "We thank you for being part of our special day",
    titlesTypography: "Playfair Display",
    namesTypography: "Inter",
    titlesColor: "#5c4a3a",
    namesColor: "#8a6252",
    titlesFontSize: 16,
    namesFontSize: 14,
    couple: {
      title: "Couple",
      groomName: "Alexander James Smith",
      groomTitle: "Groom",
      brideName: "Isabella Marie Johnson",
      brideTitle: "Bride",
    },
    groomParents: {
      title: "Parents of the Groom",
      fatherName: "Robert Smith",
      fatherTitle: "Mr.",
      motherName: "Elizabeth Smith",
      motherTitle: "Mrs.",
    },
    brideParents: {
      title: "Parents of the Bride",
      fatherName: "Michael Johnson",
      fatherTitle: "Mr.",
      motherName: "Sarah Johnson",
      motherTitle: "Mrs.",
    },
  },
  footerDivider: "none",
  universalDivider: "none",
  welcomeScreenType: "classic-envelope",
};

export const createDemoInvitation = (): Invitation => ({
  id: DEMO_INVITATION_ID,
  slug: DEMO_SLUG,
  accessCode: "DEMO",
  templateId: "demo",
  eventType: "wedding",
  clientName: "Demo Couple",
  data: demoInvitationData,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
});

export const loadDemoInvitation = (): Invitation => {
  if (typeof window === "undefined") return createDemoInvitation();
  const stored = localStorage.getItem(DEMO_STORAGE_KEY);
  if (stored) {
    try {
      const parsed = JSON.parse(stored);
      return { ...createDemoInvitation(), data: { ...demoInvitationData, ...parsed.data } };
    } catch {
      return createDemoInvitation();
    }
  }
  return createDemoInvitation();
};

export const saveDemoInvitation = (data: InvitationData): void => {
  if (typeof window === "undefined") return;
  localStorage.setItem(DEMO_STORAGE_KEY, JSON.stringify({ data }));
};

export const clearDemoInvitation = (): void => {
  if (typeof window === "undefined") return;
  localStorage.removeItem(DEMO_STORAGE_KEY);
};
